name: slack
version: 2.0.0

description: |-
  Package for accessing and utilizing the Slack webhook API.
homepage: https://github.com/ChildrenOfUr/dart-slack

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.4

dev-dependencies:
  build_runner: '>=0.8.10 <2.0.0'
  build_web_compilers: '>=0.3.6 <2.0.0'